name: ccwc - main

on:
  push:
    branches: ["main"]

jobs:
  quality:
    uses: ./.github/workflows/_quality.yaml
  release:
    runs-on: ubuntu-latest
    needs: quality
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
