name: pull request

on:
  pull_request:
    branches: ["main"]

jobs:
  quality:
    uses: ./.github/workflows/_quality.yaml
  integration-tests:
    uses: ./.github/workflows/_integration-tests.yaml
    permissions:
      pull-requests: write
